#! /bin/zsh
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# let ssh know we are suing gpg-agent
# unset SSH_AGENT_PID
# if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
#   export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
# fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Detect terminal program and load appropriate shell integration
# case "$TERM_PROGRAM" in
# "WarpTerminal")
#   # Add Warp Terminal specific integration if needed
#   return
#   ;;
# "Ghostty")
#   # Add Ghostty shell integration for zsh
#   [[ -f "${XDG_CONFIG_HOME}/zsh/ghostty/ghostty-integration" ]] && source "${XDG_HOME_CONFIG}/zsh/ghostty/ghostty-integration"
#   ;;
# "Kitty")
#   # Add Warp Terminal specific integration if needed
#   return
#   ;;
# "iTerm.app")
#   # Add iTerm2 Terminal specific integration if needed
#   [[ -f "${XDG_HOME_CONFIG}/zsh/iterm2/.iterm2_shell_integration.zsh" ]] && source "$HOME/.config/iterm2/.iterm2_shell_integration.zsh"
#   ;;
# "Apple_Terminal")
#   # Add Apple Terminal specific integration if needed
#   return
#   ;;
# "Hyper")
#   # Add Hyper specific integration if needed
#   return
#   ;;
# *)
#   # Default case for other terminal programs
#   return
#   ;;
# esac

## Ghostty shell integration for zsh. This should be at the top of your bashrc!
if [ -n "${GHOSTTY_RESOURCES_DIR}" ]; then
    builtin source "${GHOSTTY_RESOURCES_DIR}/shell-integration/zsh/ghostty-integration"
fi
# builtin source ${XDG_CONFIG_HOME}/zsh/ghostty/ghostty-integration

# if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
#   ##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW
#   source "${XDG_CONFIG_HOME}/zsh/.iterm2/.iterm2_shell_integration.zsh"
#   #​#### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
# fi    ## removed from above  */ ​test -e "${HOME}/.config/zsh.d/.iterm2/.iterm2_shell_integration.zsh" && /*

## load aliases
[[ -f "${XDG_CONFIG_HOME}/zsh/aliases.zsh" ]] && source "${XDG_CONFIG_HOME}/zsh/aliases.zsh"
[[ -f "${XDG_CONFIG_HOME}/functions.zsh" ]] && source "${XDG_CONFIG_HOME}/functions.zsh"
[[ -f "${XDG_CONFIG_HOME}/starship/starship.zsh" ]] && source "${XDG_CONFIG_HOME}/starship/starship.zsh"

## Start things....
source <(fzf --zsh)
eval "$(zoxide init --cmd cd zsh)"
eval "$(starship init zsh)"
eval "$(atuin init zsh)"
eval "$(thefuck --alias)"
# eval "$(emplace init zsh)"

# For zsh subshells, add to ~/.zshrc.
printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "zsh"}}\x9c'
