#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
test -e "${HOME}/.config/iterm2/.iterm2_shell_integration.zsh" && source "${HOME}/.config/iterm2/.iterm2_shell_integration.zsh"


[[ -f ~/.config/zsh/aliases.zsh ]] && source ~/.config/zsh/aliases.zsh
[[ -f ~/.config/zsh/functions.zsh ]] && source ~/.config/zsh/functions.zsh
[[ -f ~/.config/zsh/starship.zsh ]] && source ~/.config/zsh/starship.zsh


### Need to taylor for Mac and Linux
# Load all .<app> files from .config/<app>.d directories
#if [ -d $ZDOTDIR ]; then
#  for file in $HOME/.config/zsh/*.zsh; do
#    source $file
#  done
#  for file in $HOME/.config/docker/*.docker; do
#    source $file
#  done
#  for file in $HOME/.config/git/*.git; do
#    source $file
#  done
#  for file in $HOME/.config/vim/*.vim; do
#    source $file
#  done
#fi

## Start things....
#eval "$(oh-my-posh init zsh)"
eval "$(starship init zsh)"